name: Coverage-Computation NewVersion

on:
  workflow_dispatch:  # allows manual triggering

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 #get all

      # Step 2: Set up Java
      - name: Set up Java 8
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '8'

      # Step 3: Run Maven tests
      - name: Run Maven tests
        run: mvn -B clean test -Dmaven.test.failure.ignore=true
          
      - name: Find jacoco.exec files
        run: find . -name jacoco.exec
        
      - name: Debug: list jacoco.exec files
        run: |
            echo "Searching for jacoco.exec files..."
            find . -type f -name jacoco.exec -print
          
      - name: List JaCoCo folders
        run: find . -type d -name jacoco
      
      # Step 4: Upload JaCoCo reports
      - name: Upload JaCoCo reports
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-reports
          path: '**/target/site/jacoco'
          if-no-files-found: ignore
          
      