name: Coverage-Computation NewVersion

on:
  workflow_dispatch:  # allows manual triggering

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 #get all

      # Step 2: Set up Java
      - name: Set up Java 8
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '8'

      # Step 3: Run Maven tests
      - name: Run Maven tests
        run: mvn -B clean verify -Pit -Dmaven.test.failure.ignore=true 

      - name: Merge Jacoco coverage
        run: mvn jacoco:merge
      
      # Step 4: Upload report
      - name: Upload Jacoco report
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-reports
          path: '**/target/site/jacoco*'
          
      #Step 5: Upload surefire reports to get failed test nr
      - name: Upload Surefire reports
        uses: actions/upload-artifact@v4
        with:
          name: surefire-reports
          path: '**/target/surefire-reports'

      - name: Upload Failsafe reports
        uses: actions/upload-artifact@v4
        with:
          name: failsafe-reports
          path: '**/target/failsafe-reports'
      
          
    
      
