name: Unit Test Coverage Computation

on:
  workflow_dispatch:  # allows manual triggering

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 #get all

      # Step 2: Set up Java
      - name: Set up Java 8
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '8'

      - name: Install Maven 3.6.3
        run: |
          curl -fsSL https://archive.apache.org/dist/maven/maven-3/3.6.3/binaries/apache-maven-3.6.3-bin.tar.gz -o maven.tar.gz
          tar -xzf maven.tar.gz
          echo "$PWD/apache-maven-3.6.3/bin" >> $GITHUB_PATH

      - name: Check Maven version
        run: mvn -version
    
      # Step 3: Run Maven tests
      - name: Run Maven tests
        run: mvn -B clean verify -DskipITs=true -Dmaven.test.failure.ignore=true --settings settings.xml
        
      - name: Generate Jacoco report
        run: mvn jacoco:report 
      
      # Step 4: Upload report
      - name: Upload Jacoco report
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-reports-${{ github.ref_name }}
          path: '**/target/site/jacoco*'
          
      #Step 5: Upload surefire reports to get failed test nr
      - name: Upload Surefire reports
        uses: actions/upload-artifact@v4
        with:
          name: surefire-reports-${{ github.ref_name }}
          path: '**/target/surefire-reports'

